### ISSUE TITLE
video.md missing

### ISSUE THREAD

**Issue by fernand0** [qgerome/err-youtube#1]
Hello,

trying the plugin with XMPP backend I've found that it fails with an error message: 

> Computer says nooo. See logs for details.: video.md

Copying video.html to video.md in templates solves the problem. But maybe video.html is not needed...

**Comment by qgerome** [comment]
Hello ! 

Thanks for the fix, could you create a PR for it ?

Regards,

**Comment by gbin** [comment]
Note: now the template should be in markdown and not xhtml-im anymore, it becomes way simpler:

`video.md`

``` markdown
[{{title}}]({{video_url}})
```

Should generate for you a link for every backend.
